import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import { Toaster } from "@/components/ui/toaster";
import Rally from "@/components/pages/home-page/Rally";
import { getHomepage } from "@/sanity/queries/homepage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { rally } = await getHomepage();

  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster />
        <Rally rally={rally} />
        <Footer />
      </body>
    </html>
  );
}
